# name: Node.js CI/CD

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   install-and-test:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x]

#     steps:
#       - uses: actions/checkout@master

#       - name: Set up Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@master
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install packages
#         run: yarn install --frozen-lockfile
      
#       - name: Install Script
#         run: yarn global add react-scripts
        
#       - name: Yarn Test
#         run: yarn test
              
#   deploy:
#     runs-on: ubuntu-20.04
#     permissions:
#       contents: write
#     concurrency:
#       group: ${{ github.workflow }}-${{ github.ref }}
#     steps:
#       - uses: actions/checkout@v3

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '14'

#       - name: Get yarn cache
#         id: yarn-cache
#         run: echo "::set-output name=dir::$(yarn cache dir)"

#       - name: Cache dependencies
#         uses: actions/cache@v2
#         with:
#           path: ${{ steps.yarn-cache.outputs.dir }}
#           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-

#       - run: yarn install --frozen-lockfile
#       - run: yarn build
#       - run: yarn export

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: ${{ github.ref == 'refs/heads/main' }}
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./out

name: Build and Deploy
on: [push]
permissions: 
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3

      - name: Install and Build üîß # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn run build

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
